### PR TITLE
Enable FUSE mounting in notebook containers

### PR DESCRIPTION
**Pull request by AlexHilson**

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
This will work. It's [not a good idea](https://lwn.net/Articles/486306/) to give the containers `CAP_SYS_ADMIN`, but it'll be fine for a temporary sticking plaster.

Will this work with less permissions?

https://docs.docker.com/engine/reference/run/#/runtime-privilege-and-linux-capabilities

**Comment by AlexHilson** [comment]
I'll take another look but all of the documentation I've seen so far uses CAP_SYS_ADMIN.

**Comment by jacobtomlinson** [comment]
`CAP_SYS_ADMIN` just means ALL THE THINGS. 

image

So you almost certainly be more granular. It's just whether it's worth the time investment right now working out which granules.

**Comment by AlexHilson** [comment]
The man pages suggest that cap_sys_admin is more of a miscellaneous bucket (with perhaps too many operations included) rather than a capability that includes everything. E.g. capabilities are not repeated in both cap_sys_admin and in other capabilities.

       CAP_SYS_ADMIN
              * Perform a range of system administration operations including: quotactl(2), mount(2), umount(2), swapon(2), swapoff(2), sethostname(2), and setdomainname(2);
               .....

There are no other references to mount in any other capabilities in man capabilities.

**Comment by jacobtomlinson** [comment]
We need a better solution long term. But this is fine for now.

**Pull request merged**
